CREATE TABLE IF NOT EXISTS MarketSnapshot (
  id BIGSERIAL PRIMARY KEY,
  timestamp TIMESTAMPTZ UNIQUE NOT NULL,
  buyPrice DOUBLE PRECISION,
  sellPrice DOUBLE PRECISION,
  spread DOUBLE PRECISION,
  medianBuy DOUBLE PRECISION,
  medianSell DOUBLE PRECISION,
  q1Buy DOUBLE PRECISION,
  q3Buy DOUBLE PRECISION,
  q1Sell DOUBLE PRECISION,
  q3Sell DOUBLE PRECISION,
  trimmedAds INTEGER DEFAULT 0,
  volume DOUBLE PRECISION
);
